name: unpub_web
description: Flutter web frontend for unpub.
version: 1.0.0
publish_to: none
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  unpub_api:
    path: ../unpub/lib/unpub_api
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
