# AWS-specific local infra for unpub_aws tests/examples.
services:
  mock_s3:
    image: adobe/s3mock
    environment:
      initialBuckets: 'dart-pub-test'
    ports:
      - "9090:9090"
      - "9191:9191"
